import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/ui/Navbar';
import { alatsi, roboto } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Conference Ticket Generator',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${roboto.className} ${roboto.variable} ${alatsi.variable} antialiased text-white min-h-screen`}
    >
      <body className='min-h-[inherit] 2md:px-[120px] md:px-14 px-5 md:pt-6 pt-2.5 md:pb-28 pb-[42px] md:space-y-[46px] space-y-[18px]'>
        <Navbar />

        <main>{children}</main>
      </body>
    </html>
  );
}
